name: Compilation & tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  nano_plugin_build:
    name: Build plugin for NanoS, X and S+
    strategy:
      matrix:
        include:
          - SDK: "$NANOS_SDK"
            artifact: nanos
          - SDK: "$NANOX_SDK"
            artifact: nanox
          - SDK: "$NANOSP_SDK"
            artifact: nanosp
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Clone SDK
        uses: actions/checkout@v2
        with:
          repository: LedgerHQ/ethereum-plugin-sdk
          path: ethereum-plugin-sdk
          ref: ${{ github.base_ref || github.ref_name }}
      - name: Build plugin for Nano S
        run: |
          make clean
          make BOLOS_SDK=${{ matrix.SDK }}

  nano_plugin_debug_build:
    name: Build plugin for NanoS, X and S+ testing
    strategy:
      matrix:
        include:
          - SDK: "$NANOS_SDK"
            artifact: nanos
          - SDK: "$NANOX_SDK"
            artifact: nanox
          - SDK: "$NANOSP_SDK"
            artifact: nanosp
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Clone SDK
        uses: actions/checkout@v2
        with:
          repository: LedgerHQ/ethereum-plugin-sdk
          path: ethereum-plugin-sdk
          ref: ${{ github.base_ref || github.ref_name }}
      - name: Build plugin
        run: |
          make clean
          make -j DEBUG=1 BOLOS_SDK=${{ matrix.SDK }}

      - name: Move binary to test directory
        run: |
          mkdir -p ./tests/elfs/
          mv bin/app.elf ./tests/elfs/plugin_${{ matrix.artifact }}.elf

      - name: Upload plugin binary
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: tests/elfs/plugin_${{ matrix.artifact }}.elf

  nano_ethereum_debug_build:
    name: Build Ethereum application for Nano S, X and S+ testing
    strategy:
      matrix:
        include:
          - SDK: "$NANOS_SDK"
            artifact: nanos
          - SDK: "$NANOX_SDK"
            artifact: nanox
          - SDK: "$NANOSP_SDK"
            artifact: nanosp
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest
    steps:
      - name: Checkout app-ethereum
        uses: actions/checkout@v2
        with:
          repository: LedgerHQ/app-ethereum
          ref: ${{ github.base_ref || github.ref_name }}
          submodules: recursive

      - name: Build ethereum
        run: |
          make clean
          make -j DEBUG=1 BYPASS_SIGNATURES=1 BOLOS_SDK=${{ matrix.SDK }} CHAIN=ethereum

      - name: Move binary to test directory
        run: |
          mkdir -p ./tests/elfs/
          mv bin/app.elf ./tests/elfs/ethereum_${{ matrix.artifact }}.elf

      - name: Upload plugin binary
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: tests/elfs/ethereum_${{ matrix.artifact }}.elf